// Create a private playlist on demand and add a bucket's tracks to it.

import { spotifyFetch } from "./api.js";

export async function getCurrentUserId(token) {
  const me = await spotifyFetch(token, "/me");
  return me.id;
}

// Creates one private playlist and adds all uris (batched at 100/request).
// Returns { url, id }.
export async function createColorPlaylist(token, { colorName, uris }) {
  const userId = await getCurrentUserId(token);

  const playlist = await spotifyFetch(token, `/users/${userId}/playlists`, {
    method: "POST",
    body: JSON.stringify({
      name: `${capitalize(colorName)} — Color Playlist`,
      public: false,
      description: "Auto-generated by album cover color.",
    }),
  });

  for (let i = 0; i < uris.length; i += 100) {
    const batch = uris.slice(i, i + 100);
    await spotifyFetch(token, `/playlists/${playlist.id}/tracks`, {
      method: "POST",
      body: JSON.stringify({ uris: batch }),
    });
  }

  return {
    id: playlist.id,
    url: playlist.external_urls?.spotify || null,
  };
}

function capitalize(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
